### PR TITLE
fix(Select): #413

### LINKED ISSUE #413: Type Errors if Select.Option are rendered both statically and dynamically
I am trying to create my own wrapper component for `<Select>` to make it more re-usable in my own app. 

```ts
// imports ...

export default function AppSelect(props: IAppSelectProps) {
  return (
    <div>
      {props.label && <label>{props.label}</label>}
      <Select {...props.selectProps}>
        <Select.Option value="" disabled>Select Item</Select.Option>
        {props.options.map((o) => (
          <Select.Option key={o.label} value={o.value} disabled={o.disabled}>
            {o.label}
          </Select.Option>
        ))}
      </Select>
      {props.errorMsg && <span className="text-error">{props.errorMsg}</span>}
    </div>
  );
}
```

This does work functionally but I am getting type errors on the dynamic mapping part of my options. 

The type error I am getting is: 
```
Type 'Element[]' is not assignable to type 'ReactElement<SelectOptionProps, string | JSXElementConstructor<any>> | (string & ReactElement<SelectOptionProps, string | JSXElementConstructor<...>>)'.
Type 'Element[]' is not assignable to type 'string & ReactElement<SelectOptionProps, string | JSXElementConstructor<any>>'.
Type 'Element[]' is not assignable to type 'string'.
```
    
 If I remove my 1 static `Select.Option` that I am using as a placeholder value than the type error goes away... I would like to keep the placeholder value and fix this type error but I am having trouble.

### PR DESCRIPTION
**Pull request by yoshi6jp**
I fixed #413

### CODE REVIEW

File: src/Select/Select.tsx [hunk 1]
```diff
@@ -11,7 +16,7 @@ export type SelectProps = Omit<
   'size' | 'color'
 > &
   IComponentBaseProps & {
-    children: ReactElement<SelectOptionProps>[]
+    children: ListOrItem<ReactElement<SelectOptionProps>>
```
Comment (victorcarvalhosp) [inline src/Select/Select.tsx:19]: awesome!

File: src/types.ts [hunk 2]
```diff
@@ -9,17 +9,19 @@ import {
...
 
-export type DataTheme = typeof DEFAULT_THEMES[number] | string
+export type DataTheme = (typeof DEFAULT_THEMES)[number] | string
 
 export interface IComponentBaseProps {
   dataTheme?: DataTheme
 }
 
-export type ComponentColor = typeof componentColors[number]
+export type ComponentColor = (typeof componentColors)[number]
```
Comment (victorcarvalhosp) [inline src/types.ts]: Are these extra () needed?

Comment (yoshi6jp) [reply src/types.ts]: 4f01cbe1bc2a1b9371cf627bd3688683bdf214bd Fixed in this commit.

**Review by benjitrosch — APPROVED** [review]
